// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy7R2dNOvUtIsge9FxTIqEyQcvYNea0jo',
    appId: '1:27041997167:web:36ec1348492fd74036489a',
    messagingSenderId: '27041997167',
    projectId: 'omeyoassignment',
    authDomain: 'omeyoassignment.firebaseapp.com',
    storageBucket: 'omeyoassignment.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOs5sw1DW2CT4qVBw5LIgvGKZSDZ3AzNc',
    appId: '1:27041997167:android:5387b40b61c4946936489a',
    messagingSenderId: '27041997167',
    projectId: 'omeyoassignment',
    storageBucket: 'omeyoassignment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApq9y28i4QdWFpFnhejsCvFgJ73GOOJLQ',
    appId: '1:27041997167:ios:84d7b8d37cbbf51936489a',
    messagingSenderId: '27041997167',
    projectId: 'omeyoassignment',
    storageBucket: 'omeyoassignment.appspot.com',
    iosBundleId: 'com.example.omeyoAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApq9y28i4QdWFpFnhejsCvFgJ73GOOJLQ',
    appId: '1:27041997167:ios:14a1e014b38e58eb36489a',
    messagingSenderId: '27041997167',
    projectId: 'omeyoassignment',
    storageBucket: 'omeyoassignment.appspot.com',
    iosBundleId: 'com.example.omeyoAssignment.RunnerTests',
  );
}
